/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/azure-robot-arms.glb --types --shadows 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'All Animations'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    __polySurface11: THREE.Mesh
    _polySurface2_1: THREE.Mesh
    _polySurface2_2: THREE.Mesh
    __polySurface13: THREE.Mesh
    _polySurface3_1: THREE.Mesh
    _polySurface3_2: THREE.Mesh
    __polySurface14: THREE.Mesh
    _polySurface4_1: THREE.Mesh
    _polySurface4_2: THREE.Mesh
    __polySurface15: THREE.Mesh
    _polySurface5_1: THREE.Mesh
    _polySurface5_2: THREE.Mesh
    __polySurface16: THREE.Mesh
    _polySurface6_1: THREE.Mesh
    _polySurface6_2: THREE.Mesh
    __polySurface17: THREE.Mesh
    _polySurface7_1: THREE.Mesh
    _polySurface7_2: THREE.Mesh
    __Misc_1: THREE.Mesh
    __Misc_2: THREE.Mesh
    __Misc_3: THREE.Mesh
    __Misc_4: THREE.Mesh
    __Misc_5: THREE.Mesh
    __Misc_6: THREE.Mesh
    __Misc_7: THREE.Mesh
    __Misc_8: THREE.Mesh
    __Misc_9: THREE.Mesh
    __Misc_10: THREE.Mesh
    __Misc_11: THREE.Mesh
    __Misc_12: THREE.Mesh
    __Misc_13: THREE.Mesh
    __Misc_14: THREE.Mesh
    __Misc_15: THREE.Mesh
    __Misc_16: THREE.Mesh
    __Misc_17: THREE.Mesh
    __Misc_18: THREE.Mesh
    __Misc_19: THREE.Mesh
    __Misc_20: THREE.Mesh
    __Table7_1: THREE.Mesh
    __Table7_2: THREE.Mesh
    __Table7_3: THREE.Mesh
    __Table7_4: THREE.Mesh
    __Table7_5: THREE.Mesh
    __Table7_6: THREE.Mesh
    __Table7_7: THREE.Mesh
    __Table7_8: THREE.Mesh
    __Table7_9: THREE.Mesh
    __Table7_10: THREE.Mesh
    __Table8_1: THREE.Mesh
    __Table8_2: THREE.Mesh
    __Table8_3: THREE.Mesh
    __Table8_4: THREE.Mesh
    __Table8_5: THREE.Mesh
    __Table8_6: THREE.Mesh
    __Table8_7: THREE.Mesh
    __Table8_8: THREE.Mesh
    __Table8_9: THREE.Mesh
    __Table8_10: THREE.Mesh
    __Table9_1: THREE.Mesh
    __Table9_2: THREE.Mesh
    __Table9_3: THREE.Mesh
    __Table9_4: THREE.Mesh
    __Table9_5: THREE.Mesh
    __Table9_6: THREE.Mesh
    __Table9_7: THREE.Mesh
    __Table9_8: THREE.Mesh
    __Table9_9: THREE.Mesh
    __Table9_10: THREE.Mesh
    __Table10_1: THREE.Mesh
    __Table10_2: THREE.Mesh
    __Table10_3: THREE.Mesh
    __Table10_4: THREE.Mesh
    __Table10_5: THREE.Mesh
    __Table10_6: THREE.Mesh
    __Table10_7: THREE.Mesh
    __Table10_8: THREE.Mesh
    __Table10_9: THREE.Mesh
    __Table10_10: THREE.Mesh
    __Table11_1: THREE.Mesh
    __Table11_2: THREE.Mesh
    __Table11_3: THREE.Mesh
    __Table11_4: THREE.Mesh
    __Table11_5: THREE.Mesh
    __Table11_6: THREE.Mesh
    __Table11_7: THREE.Mesh
    __Table11_8: THREE.Mesh
    __Table11_9: THREE.Mesh
    __Table11_10: THREE.Mesh
    _polySurface8_1: THREE.Mesh
    _polySurface8_2: THREE.Mesh
    _polySurface8_3: THREE.Mesh
    _polySurface8_4: THREE.Mesh
    _polySurface8_5: THREE.Mesh
    _polySurface8_6: THREE.Mesh
    _polySurface8_7: THREE.Mesh
    _polySurface8_8: THREE.Mesh
    _polySurface9_1: THREE.Mesh
    _polySurface9_2: THREE.Mesh
  }
  materials: {
    ['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
    ['New11:OpaqueFBXASC040160FBXASC044160FBXASC0441600']: THREE.MeshStandardMaterial
    ['New11:OpaqueFBXASC040246FBXASC044246FBXASC044243FBXASC041']: THREE.MeshStandardMaterial
    ['New11:OpaqueFBXASC04033FBXASC04419FBXASC0446FBXASC041']: THREE.MeshStandardMaterial
    ['New11:OpaqueFBXASC04025FBXASC04425FBXASC04425FBXASC043']: THREE.MeshStandardMaterial
    ['New11:OpaqueFBXASC040191FBXASC044191FBXASC044191FBXASC041']: THREE.MeshStandardMaterial
    ['New11:Default_Material8']: THREE.MeshStandardMaterial
    ['New11:lambert12']: THREE.MeshStandardMaterial
    ['New11:OpaqueFBXASC04068FBXASC044150FBXASC04472FBXASC041']: THREE.MeshStandardMaterial
    ['New11:OpaqueFBXASC040232FBXASC044173FBXASC04435FBXASC041']: THREE.MeshStandardMaterial
    ['New11:OpaqueFBXASC040190FBXASC044188FBXASC044186FBXASC041']: THREE.MeshStandardMaterial
    ['New11:OpaqueFBXASC040137FBXASC044137FBXASC044137FBXASC041']: THREE.MeshStandardMaterial
    ['New11:OpaqueFBXASC04048FBXASC04459FBXASC044150FBXASC041']: THREE.MeshStandardMaterial
    ['New11:OpaqueFBXASC040128FBXASC04481FBXASC04432FBXASC041']: THREE.MeshStandardMaterial
    ['New11:OpaqueFBXASC040196FBXASC04453FBXASC04439FBXASC041']: THREE.MeshStandardMaterial
    ['New11:lambert13']: THREE.MeshStandardMaterial
    ['New11:OpaqueFBXASC040153FBXASC044153FBXASC044153FBXASC042']: THREE.MeshStandardMaterial
    ['New11:lambert11']: THREE.MeshStandardMaterial
    ['New11:lambert14']: THREE.MeshStandardMaterial
    ['New11:lambert15']: THREE.MeshStandardMaterial
    ['New11:lambert8']: THREE.MeshStandardMaterial
    ['New11:CoatingFBXASC032FBXASC045FBXASC032BlackFBXASC032Oxide1']: THREE.MeshStandardMaterial
    ['New11:PlasticFBXASC032FBXASC045FBXASC032GlossyFBXASC032FBXASC040BlackFBXASC044']: THREE.MeshStandardMaterial
    ['New11:lambert7']: THREE.MeshStandardMaterial
    ['New11:AluminumFBXASC032FBXASC045FBXASC032Satin3']: THREE.MeshStandardMaterial
    ['New11:lambert9']: THREE.MeshStandardMaterial
    ['New11:ABSFBXASC032FBXASC040WhiteFBXASC042']: THREE.MeshStandardMaterial
    ['New11:Default_Material9']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/azure-robot-arms.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="_group7" position={[-13.645, 7.7, 14.886]} rotation={[0, 1.048, 0]}>
          <group name="_group1" position={[-6.327, 0, -13.018]}>
            <mesh name="__polySurface11" castShadow receiveShadow geometry={nodes.__polySurface11.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} position={[0.016, -7.651, -2.062]} rotation={[-0.127, -0.098, 0.281]} />
            <group name="_polySurface2">
              <mesh name="_polySurface2_1" castShadow receiveShadow geometry={nodes._polySurface2_1.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} />
              <mesh name="_polySurface2_2" castShadow receiveShadow geometry={nodes._polySurface2_2.geometry} material={materials.lambert1} />
            </group>
          </group>
          <group name="_group2" position={[-6.318, 0, -6.62]}>
            <mesh name="__polySurface13" castShadow receiveShadow geometry={nodes.__polySurface13.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} position={[0.385, -1.203, -1.915]} rotation={[-0.002, -0.087, 0.055]} />
            <group name="_polySurface3">
              <mesh name="_polySurface3_1" castShadow receiveShadow geometry={nodes._polySurface3_1.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} />
              <mesh name="_polySurface3_2" castShadow receiveShadow geometry={nodes._polySurface3_2.geometry} material={materials.lambert1} />
            </group>
          </group>
          <group name="_group3" position={[-5.305, 0, 18.446]} rotation={[0, 0.826, 0]}>
            <mesh name="__polySurface14" castShadow receiveShadow geometry={nodes.__polySurface14.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} position={[0.41, -1.247, -1.899]} rotation={[-0.002, -0.087, 0.055]} />
            <group name="_polySurface4">
              <mesh name="_polySurface4_1" castShadow receiveShadow geometry={nodes._polySurface4_1.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} />
              <mesh name="_polySurface4_2" castShadow receiveShadow geometry={nodes._polySurface4_2.geometry} material={materials.lambert1} />
            </group>
          </group>
          <group name="_group4" position={[0, 0, -13.005]}>
            <mesh name="__polySurface15" castShadow receiveShadow geometry={nodes.__polySurface15.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} position={[0.424, -1.281, -1.888]} rotation={[-0.002, -0.087, 0.055]} />
            <group name="_polySurface5">
              <mesh name="_polySurface5_1" castShadow receiveShadow geometry={nodes._polySurface5_1.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} />
              <mesh name="_polySurface5_2" castShadow receiveShadow geometry={nodes._polySurface5_2.geometry} material={materials.lambert1} />
            </group>
          </group>
          <group name="_group5" position={[0, 0, -6.618]}>
            <mesh name="__polySurface16" castShadow receiveShadow geometry={nodes.__polySurface16.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} position={[0.016, -7.651, -2.062]} rotation={[-0.127, -0.098, 0.281]} />
            <group name="_polySurface6">
              <mesh name="_polySurface6_1" castShadow receiveShadow geometry={nodes._polySurface6_1.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} />
              <mesh name="_polySurface6_2" castShadow receiveShadow geometry={nodes._polySurface6_2.geometry} material={materials.lambert1} />
            </group>
          </group>
          <group name="_group6">
            <mesh name="__polySurface17" castShadow receiveShadow geometry={nodes.__polySurface17.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} position={[-0.016, -7.596, -2.082]} rotation={[-0.127, -0.098, 0.281]} />
            <group name="_polySurface7">
              <mesh name="_polySurface7_1" castShadow receiveShadow geometry={nodes._polySurface7_1.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} />
              <mesh name="_polySurface7_2" castShadow receiveShadow geometry={nodes._polySurface7_2.geometry} material={materials.lambert1} />
            </group>
          </group>
          <group name="__Misc" position={[-6.318, 0, -13.005]}>
            <mesh name="__Misc_1" castShadow receiveShadow geometry={nodes.__Misc_1.geometry} material={materials['New11:OpaqueFBXASC040160FBXASC044160FBXASC0441600']} />
            <mesh name="__Misc_2" castShadow receiveShadow geometry={nodes.__Misc_2.geometry} material={materials.lambert1} />
            <mesh name="__Misc_3" castShadow receiveShadow geometry={nodes.__Misc_3.geometry} material={materials['New11:OpaqueFBXASC040246FBXASC044246FBXASC044243FBXASC041']} />
            <mesh name="__Misc_4" castShadow receiveShadow geometry={nodes.__Misc_4.geometry} material={materials['New11:OpaqueFBXASC04033FBXASC04419FBXASC0446FBXASC041']} />
            <mesh name="__Misc_5" castShadow receiveShadow geometry={nodes.__Misc_5.geometry} material={materials['New11:OpaqueFBXASC04025FBXASC04425FBXASC04425FBXASC043']} />
            <mesh name="__Misc_6" castShadow receiveShadow geometry={nodes.__Misc_6.geometry} material={materials['New11:OpaqueFBXASC040191FBXASC044191FBXASC044191FBXASC041']} />
            <mesh name="__Misc_7" castShadow receiveShadow geometry={nodes.__Misc_7.geometry} material={materials['New11:Default_Material8']} />
            <mesh name="__Misc_8" castShadow receiveShadow geometry={nodes.__Misc_8.geometry} material={materials['New11:lambert12']} />
            <mesh name="__Misc_9" castShadow receiveShadow geometry={nodes.__Misc_9.geometry} material={materials['New11:OpaqueFBXASC04068FBXASC044150FBXASC04472FBXASC041']} />
            <mesh name="__Misc_10" castShadow receiveShadow geometry={nodes.__Misc_10.geometry} material={materials['New11:OpaqueFBXASC040232FBXASC044173FBXASC04435FBXASC041']} />
            <mesh name="__Misc_11" castShadow receiveShadow geometry={nodes.__Misc_11.geometry} material={materials['New11:OpaqueFBXASC040190FBXASC044188FBXASC044186FBXASC041']} />
            <mesh name="__Misc_12" castShadow receiveShadow geometry={nodes.__Misc_12.geometry} material={materials['New11:OpaqueFBXASC040137FBXASC044137FBXASC044137FBXASC041']} />
            <mesh name="__Misc_13" castShadow receiveShadow geometry={nodes.__Misc_13.geometry} material={materials['New11:OpaqueFBXASC04048FBXASC04459FBXASC044150FBXASC041']} />
            <mesh name="__Misc_14" castShadow receiveShadow geometry={nodes.__Misc_14.geometry} material={materials['New11:OpaqueFBXASC040128FBXASC04481FBXASC04432FBXASC041']} />
            <mesh name="__Misc_15" castShadow receiveShadow geometry={nodes.__Misc_15.geometry} material={materials['New11:OpaqueFBXASC040196FBXASC04453FBXASC04439FBXASC041']} />
            <mesh name="__Misc_16" castShadow receiveShadow geometry={nodes.__Misc_16.geometry} material={materials['New11:lambert13']} />
            <mesh name="__Misc_17" castShadow receiveShadow geometry={nodes.__Misc_17.geometry} material={materials['New11:OpaqueFBXASC040153FBXASC044153FBXASC044153FBXASC042']} />
            <mesh name="__Misc_18" castShadow receiveShadow geometry={nodes.__Misc_18.geometry} material={materials['New11:lambert11']} />
            <mesh name="__Misc_19" castShadow receiveShadow geometry={nodes.__Misc_19.geometry} material={materials['New11:lambert14']} />
            <mesh name="__Misc_20" castShadow receiveShadow geometry={nodes.__Misc_20.geometry} material={materials['New11:lambert15']} />
          </group>
          <group name="__Table7" position={[-6.318, 0, -13.005]}>
            <mesh name="__Table7_1" castShadow receiveShadow geometry={nodes.__Table7_1.geometry} material={materials['New11:lambert8']} />
            <mesh name="__Table7_2" castShadow receiveShadow geometry={nodes.__Table7_2.geometry} material={materials['New11:CoatingFBXASC032FBXASC045FBXASC032BlackFBXASC032Oxide1']} />
            <mesh name="__Table7_3" castShadow receiveShadow geometry={nodes.__Table7_3.geometry} material={materials['New11:PlasticFBXASC032FBXASC045FBXASC032GlossyFBXASC032FBXASC040BlackFBXASC044']} />
            <mesh name="__Table7_4" castShadow receiveShadow geometry={nodes.__Table7_4.geometry} material={materials['New11:lambert7']} />
            <mesh name="__Table7_5" castShadow receiveShadow geometry={nodes.__Table7_5.geometry} material={materials['New11:AluminumFBXASC032FBXASC045FBXASC032Satin3']} />
            <mesh name="__Table7_6" castShadow receiveShadow geometry={nodes.__Table7_6.geometry} material={materials['New11:lambert9']} />
            <mesh name="__Table7_7" castShadow receiveShadow geometry={nodes.__Table7_7.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} />
            <mesh name="__Table7_8" castShadow receiveShadow geometry={nodes.__Table7_8.geometry} material={materials.lambert1} />
            <mesh name="__Table7_9" castShadow receiveShadow geometry={nodes.__Table7_9.geometry} material={materials['New11:ABSFBXASC032FBXASC040WhiteFBXASC042']} />
            <mesh name="__Table7_10" castShadow receiveShadow geometry={nodes.__Table7_10.geometry} material={materials['New11:Default_Material9']} />
          </group>
          <group name="__Table8" position={[-6.318, 0, -13.005]}>
            <mesh name="__Table8_1" castShadow receiveShadow geometry={nodes.__Table8_1.geometry} material={materials['New11:lambert8']} />
            <mesh name="__Table8_2" castShadow receiveShadow geometry={nodes.__Table8_2.geometry} material={materials['New11:CoatingFBXASC032FBXASC045FBXASC032BlackFBXASC032Oxide1']} />
            <mesh name="__Table8_3" castShadow receiveShadow geometry={nodes.__Table8_3.geometry} material={materials['New11:PlasticFBXASC032FBXASC045FBXASC032GlossyFBXASC032FBXASC040BlackFBXASC044']} />
            <mesh name="__Table8_4" castShadow receiveShadow geometry={nodes.__Table8_4.geometry} material={materials['New11:lambert7']} />
            <mesh name="__Table8_5" castShadow receiveShadow geometry={nodes.__Table8_5.geometry} material={materials['New11:AluminumFBXASC032FBXASC045FBXASC032Satin3']} />
            <mesh name="__Table8_6" castShadow receiveShadow geometry={nodes.__Table8_6.geometry} material={materials['New11:lambert9']} />
            <mesh name="__Table8_7" castShadow receiveShadow geometry={nodes.__Table8_7.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} />
            <mesh name="__Table8_8" castShadow receiveShadow geometry={nodes.__Table8_8.geometry} material={materials.lambert1} />
            <mesh name="__Table8_9" castShadow receiveShadow geometry={nodes.__Table8_9.geometry} material={materials['New11:ABSFBXASC032FBXASC040WhiteFBXASC042']} />
            <mesh name="__Table8_10" castShadow receiveShadow geometry={nodes.__Table8_10.geometry} material={materials['New11:Default_Material9']} />
          </group>
          <group name="__Table9" position={[-6.318, 0, -13.005]}>
            <mesh name="__Table9_1" castShadow receiveShadow geometry={nodes.__Table9_1.geometry} material={materials['New11:lambert8']} />
            <mesh name="__Table9_2" castShadow receiveShadow geometry={nodes.__Table9_2.geometry} material={materials['New11:CoatingFBXASC032FBXASC045FBXASC032BlackFBXASC032Oxide1']} />
            <mesh name="__Table9_3" castShadow receiveShadow geometry={nodes.__Table9_3.geometry} material={materials['New11:PlasticFBXASC032FBXASC045FBXASC032GlossyFBXASC032FBXASC040BlackFBXASC044']} />
            <mesh name="__Table9_4" castShadow receiveShadow geometry={nodes.__Table9_4.geometry} material={materials['New11:lambert7']} />
            <mesh name="__Table9_5" castShadow receiveShadow geometry={nodes.__Table9_5.geometry} material={materials['New11:AluminumFBXASC032FBXASC045FBXASC032Satin3']} />
            <mesh name="__Table9_6" castShadow receiveShadow geometry={nodes.__Table9_6.geometry} material={materials['New11:lambert9']} />
            <mesh name="__Table9_7" castShadow receiveShadow geometry={nodes.__Table9_7.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} />
            <mesh name="__Table9_8" castShadow receiveShadow geometry={nodes.__Table9_8.geometry} material={materials.lambert1} />
            <mesh name="__Table9_9" castShadow receiveShadow geometry={nodes.__Table9_9.geometry} material={materials['New11:ABSFBXASC032FBXASC040WhiteFBXASC042']} />
            <mesh name="__Table9_10" castShadow receiveShadow geometry={nodes.__Table9_10.geometry} material={materials['New11:Default_Material9']} />
          </group>
          <group name="__Table10" position={[-6.318, 0, -13.005]}>
            <mesh name="__Table10_1" castShadow receiveShadow geometry={nodes.__Table10_1.geometry} material={materials['New11:lambert8']} />
            <mesh name="__Table10_2" castShadow receiveShadow geometry={nodes.__Table10_2.geometry} material={materials['New11:CoatingFBXASC032FBXASC045FBXASC032BlackFBXASC032Oxide1']} />
            <mesh name="__Table10_3" castShadow receiveShadow geometry={nodes.__Table10_3.geometry} material={materials['New11:PlasticFBXASC032FBXASC045FBXASC032GlossyFBXASC032FBXASC040BlackFBXASC044']} />
            <mesh name="__Table10_4" castShadow receiveShadow geometry={nodes.__Table10_4.geometry} material={materials['New11:lambert7']} />
            <mesh name="__Table10_5" castShadow receiveShadow geometry={nodes.__Table10_5.geometry} material={materials['New11:AluminumFBXASC032FBXASC045FBXASC032Satin3']} />
            <mesh name="__Table10_6" castShadow receiveShadow geometry={nodes.__Table10_6.geometry} material={materials['New11:lambert9']} />
            <mesh name="__Table10_7" castShadow receiveShadow geometry={nodes.__Table10_7.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} />
            <mesh name="__Table10_8" castShadow receiveShadow geometry={nodes.__Table10_8.geometry} material={materials.lambert1} />
            <mesh name="__Table10_9" castShadow receiveShadow geometry={nodes.__Table10_9.geometry} material={materials['New11:ABSFBXASC032FBXASC040WhiteFBXASC042']} />
            <mesh name="__Table10_10" castShadow receiveShadow geometry={nodes.__Table10_10.geometry} material={materials['New11:Default_Material9']} />
          </group>
          <group name="__Table11" position={[-6.318, 0, -13.005]}>
            <mesh name="__Table11_1" castShadow receiveShadow geometry={nodes.__Table11_1.geometry} material={materials['New11:lambert8']} />
            <mesh name="__Table11_2" castShadow receiveShadow geometry={nodes.__Table11_2.geometry} material={materials['New11:CoatingFBXASC032FBXASC045FBXASC032BlackFBXASC032Oxide1']} />
            <mesh name="__Table11_3" castShadow receiveShadow geometry={nodes.__Table11_3.geometry} material={materials['New11:PlasticFBXASC032FBXASC045FBXASC032GlossyFBXASC032FBXASC040BlackFBXASC044']} />
            <mesh name="__Table11_4" castShadow receiveShadow geometry={nodes.__Table11_4.geometry} material={materials['New11:lambert7']} />
            <mesh name="__Table11_5" castShadow receiveShadow geometry={nodes.__Table11_5.geometry} material={materials['New11:AluminumFBXASC032FBXASC045FBXASC032Satin3']} />
            <mesh name="__Table11_6" castShadow receiveShadow geometry={nodes.__Table11_6.geometry} material={materials['New11:lambert9']} />
            <mesh name="__Table11_7" castShadow receiveShadow geometry={nodes.__Table11_7.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} />
            <mesh name="__Table11_8" castShadow receiveShadow geometry={nodes.__Table11_8.geometry} material={materials.lambert1} />
            <mesh name="__Table11_9" castShadow receiveShadow geometry={nodes.__Table11_9.geometry} material={materials['New11:ABSFBXASC032FBXASC040WhiteFBXASC042']} />
            <mesh name="__Table11_10" castShadow receiveShadow geometry={nodes.__Table11_10.geometry} material={materials['New11:Default_Material9']} />
          </group>
          <group name="_polySurface8" position={[-6.318, 0, -13.005]}>
            <mesh name="_polySurface8_1" castShadow receiveShadow geometry={nodes._polySurface8_1.geometry} material={materials['New11:lambert8']} />
            <mesh name="_polySurface8_2" castShadow receiveShadow geometry={nodes._polySurface8_2.geometry} material={materials['New11:CoatingFBXASC032FBXASC045FBXASC032BlackFBXASC032Oxide1']} />
            <mesh name="_polySurface8_3" castShadow receiveShadow geometry={nodes._polySurface8_3.geometry} material={materials['New11:PlasticFBXASC032FBXASC045FBXASC032GlossyFBXASC032FBXASC040BlackFBXASC044']} />
            <mesh name="_polySurface8_4" castShadow receiveShadow geometry={nodes._polySurface8_4.geometry} material={materials['New11:lambert7']} />
            <mesh name="_polySurface8_5" castShadow receiveShadow geometry={nodes._polySurface8_5.geometry} material={materials['New11:AluminumFBXASC032FBXASC045FBXASC032Satin3']} />
            <mesh name="_polySurface8_6" castShadow receiveShadow geometry={nodes._polySurface8_6.geometry} material={materials['New11:lambert9']} />
            <mesh name="_polySurface8_7" castShadow receiveShadow geometry={nodes._polySurface8_7.geometry} material={materials['New11:ABSFBXASC032FBXASC040WhiteFBXASC042']} />
            <mesh name="_polySurface8_8" castShadow receiveShadow geometry={nodes._polySurface8_8.geometry} material={materials['New11:Default_Material9']} />
          </group>
          <group name="_polySurface9" position={[-6.318, 0, -13.005]}>
            <mesh name="_polySurface9_1" castShadow receiveShadow geometry={nodes._polySurface9_1.geometry} material={materials['New11:SiliconeFBXASC032FBXASC040WhiteFBXASC042']} />
            <mesh name="_polySurface9_2" castShadow receiveShadow geometry={nodes._polySurface9_2.geometry} material={materials.lambert1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/azure-robot-arms.glb')
