/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/microsoft-robot-arm.glb --types --shadows 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    polySurface718: THREE.Mesh
    LP_Top_low: THREE.Mesh
  }
  materials: {
    bottom: THREE.MeshStandardMaterial
    top: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/microsoft-robot-arm.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.polySurface718.geometry} material={materials.bottom} rotation={[Math.PI / 2, 0, 0]} scale={1.099} />
      <mesh castShadow receiveShadow geometry={nodes.LP_Top_low.geometry} material={materials.top} rotation={[Math.PI / 2, 0, 0]} scale={1.099} />
    </group>
  )
}

useGLTF.preload('/microsoft-robot-arm.glb')
