/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/roboparadigm-7dof.glb --draco 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import * as THREE from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/roboparadigm-7dof.glb')

  const meshRefs = React.useRef({})
  const restPose = React.useRef({})
  const assemblyOrder = React.useRef({})
  const zoneMap = React.useRef({})
  const smoothProgress = React.useRef(0)
  const { viewport } = useThree()

  // Brand colors that match the logo and website theme
  const premiumMaterials = React.useMemo(() => ({
    gunmetal: new THREE.MeshStandardMaterial({
      color: '#1e3a5f',   // Navy blue
      metalness: 0.6,
      roughness: 0.35,
      envMapIntensity: 1.5
    }),
    darkCopper: new THREE.MeshStandardMaterial({
      color: '#d4884c',   // Bright copper/gold
      metalness: 0.7,
      roughness: 0.25,
      envMapIntensity: 1.8
    }),
    warmGray: new THREE.MeshStandardMaterial({
      color: '#8b5e3c',   // Darker copper/bronze accent
      metalness: 0.8,
      roughness: 0.3,
      envMapIntensity: 1.2
    })
  }), [])

  const setRef = (el, name, order, zone) => {
    if (el && !meshRefs.current[name]) {
      meshRefs.current[name] = el
      restPose.current[name] = {
        px: el.position.x,
        py: el.position.y,
        pz: el.position.z,
        rx: el.rotation.x,
        ry: el.rotation.y,
        rz: el.rotation.z,
      }
      assemblyOrder.current[name] = order
      zoneMap.current[name] = zone
    } else if (el) {
      meshRefs.current[name] = el
    }
  }

  function smoothstep(x) {
    const t = Math.max(0, Math.min(1, x));
    return t * t * (3 - 2 * t);
  }

  function clamp(val, min, max) {
    return Math.max(min, Math.min(max, val));
  }

  function hashStr(str) {
    let h = 2166136261;
    for (let i = 0; i < str.length; i++) {
      h ^= str.charCodeAt(i);
      h = Math.imul(h, 16777619) >>> 0;
    }
    return h;
  }

  useFrame(() => {
    const target = props.scrollYProgress ? props.scrollYProgress.get() : 0;
    smoothProgress.current += (target - smoothProgress.current) * 0.06;

    const globalProgress = 1 - smoothstep(smoothProgress.current);

    const groupScale = props.groupScale || 0.018;
    const scatterX = (viewport.width / groupScale) * 0.45;
    const scatterY = (viewport.height / groupScale) * 0.38;

    const entries = Object.entries(meshRefs.current);

    entries.forEach(([name, ref]) => {
      const rest = restPose.current[name];
      const order = assemblyOrder.current[name] || 0.5;
      const zone = zoneMap.current[name] || 0;
      if (!ref || !rest) return;

      // Sequential assembly
      const assemblyStart = 0.12 + order * 0.72;
      const assemblyWindow = 0.18;
      let partProgress = clamp((globalProgress - assemblyStart) / assemblyWindow, 0, 1);
      partProgress = smoothstep(partProgress);

      // Per-part jitter from hash
      const h = hashStr(name);
      const jX = ((h % 1000) / 1000 - 0.5) * 2;
      const jY = (((h >> 10) % 1000) / 1000 - 0.5) * 2;
      const jZ = (((h >> 20) % 1000) / 1000 - 0.5) * 2;

      let dx = 0, dy = 0, dz = 0;

      // Zone-based scatter - GUARANTEED left/right balance via round-robin
      if (zone === 0) {
        // Deep Left
        dx = -scatterX * (0.6 + Math.abs(jX) * 0.4);
        dy = scatterY * jY * 0.4;
        dz = -250 + jZ * 150;
      } else if (zone === 1) {
        // Deep Right
        dx = scatterX * (0.6 + Math.abs(jX) * 0.4);
        dy = scatterY * jY * 0.4;
        dz = -250 + jZ * 150;
      } else if (zone === 2) {
        // Top-Left
        dx = -scatterX * jX * 0.4;
        dy = scatterY * (0.5 + Math.abs(jY) * 0.5);
        dz = -180 + jZ * 120;
      } else if (zone === 3) {
        // Top-Right
        dx = scatterX * Math.abs(jX) * 0.4;
        dy = scatterY * (0.5 + Math.abs(jY) * 0.5);
        dz = -180 + jZ * 120;
      } else if (zone === 4) {
        // Bottom-Left
        dx = -scatterX * Math.abs(jX) * 0.4;
        dy = -scatterY * (0.5 + Math.abs(jY) * 0.5);
        dz = -180 + jZ * 120;
      } else {
        // Bottom-Right
        dx = scatterX * Math.abs(jX) * 0.4;
        dy = -scatterY * (0.5 + Math.abs(jY) * 0.5);
        dz = -180 + jZ * 120;
      }

      ref.position.set(
        rest.px + dx * partProgress,
        rest.py + dy * partProgress,
        rest.pz + dz * partProgress
      );

      ref.rotation.set(
        rest.rx + jX * Math.PI * 0.3 * partProgress,
        rest.ry + jY * Math.PI * 0.3 * partProgress,
        rest.rz + jZ * Math.PI * 0.2 * partProgress
      );
    });
  });

  return (
    <group {...props} dispose={null}>
      <mesh ref={(el) => setRef(el, "Arm004", 0.6855, 1)} geometry={nodes.Arm004.geometry} material={premiumMaterials.darkCopper} position={[-1.735, 255.327, 38.378]} />
      <mesh ref={(el) => setRef(el, "Arm005", 0.6290, 4)} geometry={nodes.Arm005.geometry} material={premiumMaterials.gunmetal} position={[-4.83, 252.492, 40.419]} />
      <mesh ref={(el) => setRef(el, "Arm006", 0.8952, 1)} geometry={nodes.Arm006.geometry} material={premiumMaterials.gunmetal} position={[10.236, 265.04, 31.385]} />
      <mesh ref={(el) => setRef(el, "Arm007", 0.8710, 4)} geometry={nodes.Arm007.geometry} material={premiumMaterials.gunmetal} position={[-0.601, 263.227, 32.691]} />
      <mesh ref={(el) => setRef(el, "Arm008", 0.7742, 2)} geometry={nodes.Arm008.geometry} material={premiumMaterials.gunmetal} position={[5.178, 260.757, 34.471]} />
      <mesh ref={(el) => setRef(el, "Arm009", 0.5968, 0)} geometry={nodes.Arm009.geometry} material={premiumMaterials.warmGray} position={[4.567, 250.057, 42.173]} />
      <mesh ref={(el) => setRef(el, "Arm010", 0.8226, 0)} geometry={nodes.Arm010.geometry} material={premiumMaterials.gunmetal} position={[6.641, 262.254, 33.402]} />
      <mesh ref={(el) => setRef(el, "Arm011", 0.7097, 4)} geometry={nodes.Arm011.geometry} material={premiumMaterials.darkCopper} position={[8.304, 255.988, 37.86]} />
      <mesh ref={(el) => setRef(el, "Arm012", 0.6774, 0)} geometry={nodes.Arm012.geometry} material={premiumMaterials.gunmetal} position={[-9.559, 253.831, 39.455]} />
      <mesh ref={(el) => setRef(el, "Arm013", 0.8871, 0)} geometry={nodes.Arm013.geometry} material={premiumMaterials.warmGray} position={[-1.935, 264.535, 31.748]} />
      <mesh ref={(el) => setRef(el, "Arm014", 0.7581, 0)} geometry={nodes.Arm014.geometry} material={premiumMaterials.darkCopper} position={[12.596, 260.456, 34.686]} />
      <mesh ref={(el) => setRef(el, "Arm017", 0.0806, 0)} geometry={nodes.Arm017.geometry} material={premiumMaterials.darkCopper} position={[2.022, -20.552, -3.263]} />
      <mesh ref={(el) => setRef(el, "Arm018", 0.1210, 1)} geometry={nodes.Arm018.geometry} material={premiumMaterials.gunmetal} position={[0.002, -1.178, -3.543]} />
      <mesh ref={(el) => setRef(el, "Arm019", 0.1290, 2)} geometry={nodes.Arm019.geometry} material={premiumMaterials.darkCopper} position={[3.482, -1.1, -6.737]} />
      <mesh ref={(el) => setRef(el, "Arm020", 0.1129, 0)} geometry={nodes.Arm020.geometry} material={premiumMaterials.warmGray} position={[-3.593, -1.35, -2.143]} />
      <mesh ref={(el) => setRef(el, "Arm021", 0.1048, 1)} geometry={nodes.Arm021.geometry} material={premiumMaterials.darkCopper} position={[-0.029, -1.565, -6.968]} />
      <mesh ref={(el) => setRef(el, "Arm022", 0.0081, 1)} geometry={nodes.Arm022.geometry} material={premiumMaterials.darkCopper} position={[-0.033, -32.015, -2.684]} />
      <mesh ref={(el) => setRef(el, "Arm023", 0.0323, 0)} geometry={nodes.Arm023.geometry} material={premiumMaterials.darkCopper} position={[-9.35, -29.6, 19.35]} />
      <mesh ref={(el) => setRef(el, "Arm024", 0.0403, 1)} geometry={nodes.Arm024.geometry} material={premiumMaterials.warmGray} position={[9.35, -29.6, 19.35]} />
      <mesh ref={(el) => setRef(el, "Arm025", 0.0161, 0)} geometry={nodes.Arm025.geometry} material={premiumMaterials.warmGray} position={[9.208, -30.135, 2.354]} />
      <mesh ref={(el) => setRef(el, "Arm026", 0.0565, 3)} geometry={nodes.Arm026.geometry} material={premiumMaterials.darkCopper} position={[10.695, -29.416, 5.683]} />
      <mesh ref={(el) => setRef(el, "Arm027", 0.0242, 1)} geometry={nodes.Arm027.geometry} material={premiumMaterials.gunmetal} position={[-9.208, -30.135, 2.354]} />
      <mesh ref={(el) => setRef(el, "Arm028", 0.0645, 4)} geometry={nodes.Arm028.geometry} material={premiumMaterials.warmGray} position={[-10.695, -29.416, 5.683]} />
      <mesh ref={(el) => setRef(el, "Arm029", 0.0484, 2)} geometry={nodes.Arm029.geometry} material={premiumMaterials.gunmetal} position={[0, -29.45, 12.25]} />
      <mesh ref={(el) => setRef(el, "Arm030", 0.0887, 1)} geometry={nodes.Arm030.geometry} material={premiumMaterials.warmGray} position={[-1.276, -11.852, -13.263]} />
      <mesh ref={(el) => setRef(el, "Arm031", 0.0726, 5)} geometry={nodes.Arm031.geometry} material={premiumMaterials.gunmetal} position={[0.072, -20.77, 7.394]} />
      <mesh ref={(el) => setRef(el, "Arm032", 0.0968, 0)} geometry={nodes.Arm032.geometry} material={premiumMaterials.gunmetal} position={[-0.006, -4.607, 12.248]} />
      <mesh ref={(el) => setRef(el, "Arm033", 0.1371, 3)} geometry={nodes.Arm033.geometry} material={premiumMaterials.warmGray} position={[0.005, 0.457, 12.241]} />
      <mesh ref={(el) => setRef(el, "Arm034", 0.0000, 0)} geometry={nodes.Arm034.geometry} material={premiumMaterials.gunmetal} position={[0.008, -33.18, 12.242]} />
      <mesh ref={(el) => setRef(el, "Arm037", 0.1613, 0)} geometry={nodes.Arm037.geometry} material={premiumMaterials.warmGray} position={[-15.65, 23.763, 8.768]} />
      <mesh ref={(el) => setRef(el, "Arm038", 0.1694, 1)} geometry={nodes.Arm038.geometry} material={premiumMaterials.gunmetal} position={[-15.4, 28.357, 15.843]} />
      <mesh ref={(el) => setRef(el, "Arm039", 0.1532, 5)} geometry={nodes.Arm039.geometry} material={premiumMaterials.darkCopper} position={[-15.185, 23.532, 12.279]} />
      <mesh ref={(el) => setRef(el, "Arm041", 0.2419, 0)} geometry={nodes.Arm041.geometry} material={premiumMaterials.gunmetal} position={[12.85, 49.85, 21.6]} />
      <mesh ref={(el) => setRef(el, "Arm042", 0.2500, 1)} geometry={nodes.Arm042.geometry} material={premiumMaterials.darkCopper} position={[12.85, 49.85, 2.9]} />
      <mesh ref={(el) => setRef(el, "Arm043", 0.1774, 0)} geometry={nodes.Arm043.geometry} material={premiumMaterials.darkCopper} position={[13.385, 32.854, 3.042]} />
      <mesh ref={(el) => setRef(el, "Arm044", 0.1935, 0)} geometry={nodes.Arm044.geometry} material={premiumMaterials.gunmetal} position={[12.666, 36.183, 1.555]} />
      <mesh ref={(el) => setRef(el, "Arm045", 0.1855, 1)} geometry={nodes.Arm045.geometry} material={premiumMaterials.warmGray} position={[13.385, 32.854, 21.458]} />
      <mesh ref={(el) => setRef(el, "Arm046", 0.2016, 1)} geometry={nodes.Arm046.geometry} material={premiumMaterials.darkCopper} position={[12.666, 36.183, 22.945]} />
      <mesh ref={(el) => setRef(el, "Arm047", 0.2339, 5)} geometry={nodes.Arm047.geometry} material={premiumMaterials.warmGray} position={[12.7, 42.75, 12.25]} />
      <mesh ref={(el) => setRef(el, "Arm048", 0.1452, 4)} geometry={nodes.Arm048.geometry} material={premiumMaterials.gunmetal} position={[-4.898, 17.237, 13.526]} />
      <mesh ref={(el) => setRef(el, "Arm049", 0.2097, 2)} geometry={nodes.Arm049.geometry} material={premiumMaterials.warmGray} position={[4.02, 37.894, 12.178]} />
      <mesh ref={(el) => setRef(el, "Arm050", 0.2258, 4)} geometry={nodes.Arm050.geometry} material={premiumMaterials.darkCopper} position={[-12.143, 42.748, 12.256]} />
      <mesh ref={(el) => setRef(el, "Group_Base", 0.2177, 3)} geometry={nodes.Group_Base.geometry} material={premiumMaterials.darkCopper} position={[-17.207, 42.741, 12.245]} />
      <mesh ref={(el) => setRef(el, "Arm053", 0.3387, 0)} geometry={nodes.Arm053.geometry} material={premiumMaterials.gunmetal} position={[1.772, 89.448, 9.237]} />
      <mesh ref={(el) => setRef(el, "Arm054", 0.3790, 3)} geometry={nodes.Arm054.geometry} material={premiumMaterials.warmGray} position={[-0.248, 108.822, 8.957]} />
      <mesh ref={(el) => setRef(el, "Arm055", 0.3871, 4)} geometry={nodes.Arm055.geometry} material={premiumMaterials.gunmetal} position={[3.232, 108.9, 5.763]} />
      <mesh ref={(el) => setRef(el, "Arm056", 0.3710, 2)} geometry={nodes.Arm056.geometry} material={premiumMaterials.darkCopper} position={[-3.843, 108.65, 10.357]} />
      <mesh ref={(el) => setRef(el, "Arm057", 0.3629, 1)} geometry={nodes.Arm057.geometry} material={premiumMaterials.gunmetal} position={[-0.279, 108.435, 5.532]} />
      <mesh ref={(el) => setRef(el, "Arm058", 0.2661, 1)} geometry={nodes.Arm058.geometry} material={premiumMaterials.gunmetal} position={[-0.283, 77.984, 9.816]} />
      <mesh ref={(el) => setRef(el, "Arm059", 0.2903, 2)} geometry={nodes.Arm059.geometry} material={premiumMaterials.gunmetal} position={[-9.6, 80.4, 31.85]} />
      <mesh ref={(el) => setRef(el, "Arm060", 0.2984, 3)} geometry={nodes.Arm060.geometry} material={premiumMaterials.darkCopper} position={[9.1, 80.4, 31.85]} />
      <mesh ref={(el) => setRef(el, "Arm061", 0.2742, 0)} geometry={nodes.Arm061.geometry} material={premiumMaterials.darkCopper} position={[8.958, 79.865, 14.854]} />
      <mesh ref={(el) => setRef(el, "Arm062", 0.3145, 5)} geometry={nodes.Arm062.geometry} material={premiumMaterials.gunmetal} position={[10.445, 80.584, 18.183]} />
      <mesh ref={(el) => setRef(el, "Arm063", 0.2823, 1)} geometry={nodes.Arm063.geometry} material={premiumMaterials.warmGray} position={[-9.458, 79.865, 14.854]} />
      <mesh ref={(el) => setRef(el, "Arm064", 0.3226, 0)} geometry={nodes.Arm064.geometry} material={premiumMaterials.darkCopper} position={[-10.945, 80.584, 18.183]} />
      <mesh ref={(el) => setRef(el, "Arm065", 0.3065, 4)} geometry={nodes.Arm065.geometry} material={premiumMaterials.warmGray} position={[-0.25, 80.55, 24.75]} />
      <mesh ref={(el) => setRef(el, "Arm066", 0.3468, 1)} geometry={nodes.Arm066.geometry} material={premiumMaterials.darkCopper} position={[-1.526, 98.148, -0.763]} />
      <mesh ref={(el) => setRef(el, "Arm067", 0.3306, 1)} geometry={nodes.Arm067.geometry} material={premiumMaterials.warmGray} position={[-0.178, 89.23, 19.894]} />
      <mesh ref={(el) => setRef(el, "Arm068", 0.3548, 0)} geometry={nodes.Arm068.geometry} material={premiumMaterials.warmGray} position={[-0.256, 105.393, 24.748]} />
      <mesh ref={(el) => setRef(el, "Arm069", 0.3952, 5)} geometry={nodes.Arm069.geometry} material={premiumMaterials.darkCopper} position={[-0.245, 110.457, 24.741]} />
      <mesh ref={(el) => setRef(el, "Arm070", 0.2581, 0)} geometry={nodes.Arm070.geometry} material={premiumMaterials.warmGray} position={[-0.242, 76.821, 24.742]} />
      <mesh ref={(el) => setRef(el, "Group_Lower_Arm", 0.6210, 3)} geometry={nodes.Group_Lower_Arm.geometry} material={premiumMaterials.gunmetal} position={[-3.552, 252.022, -1.987]} />
      <mesh ref={(el) => setRef(el, "Arm073", 0.6694, 1)} geometry={nodes.Arm073.geometry} material={premiumMaterials.warmGray} position={[15.9, 253.482, 1.487]} />
      <mesh ref={(el) => setRef(el, "Arm074", 0.4677, 4)} geometry={nodes.Arm074.geometry} material={premiumMaterials.darkCopper} position={[15.65, 246.407, -3.107]} />
      <mesh ref={(el) => setRef(el, "Arm075", 0.5726, 1)} geometry={nodes.Arm075.geometry} material={premiumMaterials.warmGray} position={[15.435, 249.971, 1.718]} />
      <mesh ref={(el) => setRef(el, "Arm077", 0.4194, 0)} geometry={nodes.Arm077.geometry} material={premiumMaterials.darkCopper} position={[-12.6, 240.65, -24.6]} />
      <mesh ref={(el) => setRef(el, "Arm078", 0.7500, 1)} geometry={nodes.Arm078.geometry} material={premiumMaterials.gunmetal} position={[-12.6, 259.35, -24.6]} />
      <mesh ref={(el) => setRef(el, "Arm079", 0.7419, 0)} geometry={nodes.Arm079.geometry} material={premiumMaterials.warmGray} position={[-13.135, 259.208, -7.604]} />
      <mesh ref={(el) => setRef(el, "Arm080", 0.7661, 1)} geometry={nodes.Arm080.geometry} material={premiumMaterials.warmGray} position={[-12.416, 260.695, -10.933]} />
      <mesh ref={(el) => setRef(el, "Arm081", 0.4274, 1)} geometry={nodes.Arm081.geometry} material={premiumMaterials.warmGray} position={[-13.135, 240.792, -7.604]} />
      <mesh ref={(el) => setRef(el, "Arm082", 0.4113, 1)} geometry={nodes.Arm082.geometry} material={premiumMaterials.gunmetal} position={[-12.416, 239.305, -10.933]} />
      <mesh ref={(el) => setRef(el, "Arm083", 0.5887, 1)} geometry={nodes.Arm083.geometry} material={premiumMaterials.darkCopper} position={[-12.45, 250, -17.5]} />
      <mesh ref={(el) => setRef(el, "Arm084", 0.5403, 3)} geometry={nodes.Arm084.geometry} material={premiumMaterials.darkCopper} position={[5.148, 248.724, 8.013]} />
      <mesh ref={(el) => setRef(el, "Arm085", 0.6048, 1)} geometry={nodes.Arm085.geometry} material={premiumMaterials.gunmetal} position={[-3.77, 250.072, -12.644]} />
      <mesh ref={(el) => setRef(el, "Arm086", 0.5806, 0)} geometry={nodes.Arm086.geometry} material={premiumMaterials.gunmetal} position={[12.393, 249.994, -17.498]} />
      <mesh ref={(el) => setRef(el, "Arm089", 0.4839, 0)} geometry={nodes.Arm089.geometry} material={premiumMaterials.gunmetal} position={[2.022, 246.987, -64.948]} />
      <mesh ref={(el) => setRef(el, "Arm090", 0.4758, 5)} geometry={nodes.Arm090.geometry} material={premiumMaterials.warmGray} position={[0.002, 246.707, -84.322]} />
      <mesh ref={(el) => setRef(el, "Arm091", 0.4435, 1)} geometry={nodes.Arm091.geometry} material={premiumMaterials.darkCopper} position={[3.482, 243.513, -84.4]} />
      <mesh ref={(el) => setRef(el, "Arm092", 0.5000, 0)} geometry={nodes.Arm092.geometry} material={premiumMaterials.warmGray} position={[-3.593, 248.107, -84.15]} />
      <mesh ref={(el) => setRef(el, "Arm093", 0.4355, 0)} geometry={nodes.Arm093.geometry} material={premiumMaterials.gunmetal} position={[-0.029, 243.282, -83.935]} />
      <mesh ref={(el) => setRef(el, "Arm094", 0.4919, 1)} geometry={nodes.Arm094.geometry} material={premiumMaterials.darkCopper} position={[-0.033, 247.566, -53.484]} />
      <mesh ref={(el) => setRef(el, "Arm095", 0.9274, 1)} geometry={nodes.Arm095.geometry} material={premiumMaterials.darkCopper} position={[-9.35, 269.6, -55.9]} />
      <mesh ref={(el) => setRef(el, "Arm096", 0.9355, 2)} geometry={nodes.Arm096.geometry} material={premiumMaterials.warmGray} position={[9.35, 269.6, -55.9]} />
      <mesh ref={(el) => setRef(el, "Arm097", 0.6371, 5)} geometry={nodes.Arm097.geometry} material={premiumMaterials.darkCopper} position={[9.208, 252.604, -55.365]} />
      <mesh ref={(el) => setRef(el, "Arm098", 0.6935, 2)} geometry={nodes.Arm098.geometry} material={premiumMaterials.warmGray} position={[10.695, 255.933, -56.084]} />
      <mesh ref={(el) => setRef(el, "Arm099", 0.6452, 0)} geometry={nodes.Arm099.geometry} material={premiumMaterials.warmGray} position={[-9.208, 252.604, -55.365]} />
      <mesh ref={(el) => setRef(el, "Arm100", 0.7016, 3)} geometry={nodes.Arm100.geometry} material={premiumMaterials.gunmetal} position={[-10.695, 255.933, -56.084]} />
      <mesh ref={(el) => setRef(el, "Arm101", 0.8629, 3)} geometry={nodes.Arm101.geometry} material={premiumMaterials.warmGray} position={[0, 262.5, -56.05]} />
      <mesh ref={(el) => setRef(el, "Arm102", 0.4032, 0)} geometry={nodes.Arm102.geometry} material={premiumMaterials.warmGray} position={[-1.276, 236.987, -73.648]} />
      <mesh ref={(el) => setRef(el, "Arm103", 0.7258, 0)} geometry={nodes.Arm103.geometry} material={premiumMaterials.gunmetal} position={[0.072, 257.644, -64.73]} />
      <mesh ref={(el) => setRef(el, "Arm104", 0.8548, 2)} geometry={nodes.Arm104.geometry} material={premiumMaterials.darkCopper} position={[-0.006, 262.498, -80.893]} />
      <mesh ref={(el) => setRef(el, "Arm106", 0.8468, 1)} geometry={nodes.Arm106.geometry} material={premiumMaterials.gunmetal} position={[0.008, 262.492, -52.32]} />
      <mesh ref={(el) => setRef(el, "Group_Lower_Arm-2", 0.8065, 0)} geometry={nodes['Group_Lower_Arm-2'].geometry} material={premiumMaterials.gunmetal} position={[-15.072, 262.248, -177.457]} />
      <mesh ref={(el) => setRef(el, "Arm109", 0.7339, 1)} geometry={nodes.Arm109.geometry} material={premiumMaterials.darkCopper} position={[-15.15, 258.768, -174.263]} />
      <mesh ref={(el) => setRef(el, "Arm110", 0.9032, 0)} geometry={nodes.Arm110.geometry} material={premiumMaterials.darkCopper} position={[-14.9, 265.843, -178.857]} />
      <mesh ref={(el) => setRef(el, "Arm111", 0.8387, 0)} geometry={nodes.Arm111.geometry} material={premiumMaterials.warmGray} position={[-14.685, 262.279, -174.032]} />
      <mesh ref={(el) => setRef(el, "Arm113", 0.9516, 4)} geometry={nodes.Arm113.geometry} material={premiumMaterials.darkCopper} position={[13.35, 271.6, -200.35]} />
      <mesh ref={(el) => setRef(el, "Arm114", 0.6532, 1)} geometry={nodes.Arm114.geometry} material={premiumMaterials.gunmetal} position={[13.35, 252.9, -200.35]} />
      <mesh ref={(el) => setRef(el, "Arm115", 0.6613, 0)} geometry={nodes.Arm115.geometry} material={premiumMaterials.darkCopper} position={[13.885, 253.042, -183.354]} />
      <mesh ref={(el) => setRef(el, "Arm116", 0.6129, 2)} geometry={nodes.Arm116.geometry} material={premiumMaterials.darkCopper} position={[13.166, 251.555, -186.683]} />
      <mesh ref={(el) => setRef(el, "Arm117", 0.9435, 3)} geometry={nodes.Arm117.geometry} material={premiumMaterials.gunmetal} position={[13.885, 271.458, -183.354]} />
      <mesh ref={(el) => setRef(el, "Arm118", 0.9597, 5)} geometry={nodes.Arm118.geometry} material={premiumMaterials.warmGray} position={[13.166, 272.945, -186.683]} />
      <mesh ref={(el) => setRef(el, "Arm119", 0.8145, 1)} geometry={nodes.Arm119.geometry} material={premiumMaterials.warmGray} position={[13.2, 262.25, -193.25]} />
      <mesh ref={(el) => setRef(el, "Arm120", 0.8790, 5)} geometry={nodes.Arm120.geometry} material={premiumMaterials.darkCopper} position={[-4.398, 263.526, -167.737]} />
      <mesh ref={(el) => setRef(el, "Arm121", 0.7823, 3)} geometry={nodes.Arm121.geometry} material={premiumMaterials.darkCopper} position={[4.52, 262.178, -188.394]} />
      <mesh ref={(el) => setRef(el, "Arm122", 0.8306, 1)} geometry={nodes.Arm122.geometry} material={premiumMaterials.darkCopper} position={[-11.643, 262.256, -193.248]} />
      <mesh ref={(el) => setRef(el, "Arm123", 0.7984, 5)} geometry={nodes.Arm123.geometry} material={premiumMaterials.gunmetal} position={[-16.707, 262.245, -193.241]} />
      <mesh ref={(el) => setRef(el, "Arm124", 0.7903, 4)} geometry={nodes.Arm124.geometry} material={premiumMaterials.warmGray} position={[16.93, 262.242, -193.242]} />
      <mesh ref={(el) => setRef(el, "Arm127", 0.9919, 1)} geometry={nodes.Arm127.geometry} material={premiumMaterials.gunmetal} position={[-3.482, 277.15, -105.763]} />
      <mesh ref={(el) => setRef(el, "Arm128", 0.9839, 0)} geometry={nodes.Arm128.geometry} material={premiumMaterials.warmGray} position={[3.593, 276.9, -110.357]} />
      <mesh ref={(el) => setRef(el, "Arm129", 0.9758, 1)} geometry={nodes.Arm129.geometry} material={premiumMaterials.darkCopper} position={[0.029, 276.685, -105.532]} />
      <mesh ref={(el) => setRef(el, "Group_Lower_Arm-1", 0.4597, 3)} geometry={nodes['Group_Lower_Arm-1'].geometry} material={premiumMaterials.gunmetal} position={[0.033, 246.235, -109.816]} />
      <mesh ref={(el) => setRef(el, "Arm131", 0.5242, 1)} geometry={nodes.Arm131.geometry} material={premiumMaterials.warmGray} position={[9.35, 248.65, -131.85]} />
      <mesh ref={(el) => setRef(el, "Arm132", 0.5323, 2)} geometry={nodes.Arm132.geometry} material={premiumMaterials.gunmetal} position={[-9.35, 248.65, -131.85]} />
      <mesh ref={(el) => setRef(el, "Arm133", 0.5081, 1)} geometry={nodes.Arm133.geometry} material={premiumMaterials.gunmetal} position={[-9.208, 248.115, -114.854]} />
      <mesh ref={(el) => setRef(el, "Arm134", 0.5565, 5)} geometry={nodes.Arm134.geometry} material={premiumMaterials.gunmetal} position={[-10.695, 248.834, -118.183]} />
      <mesh ref={(el) => setRef(el, "Arm135", 0.5161, 0)} geometry={nodes.Arm135.geometry} material={premiumMaterials.darkCopper} position={[9.208, 248.115, -114.854]} />
      <mesh ref={(el) => setRef(el, "Arm136", 0.5645, 0)} geometry={nodes.Arm136.geometry} material={premiumMaterials.darkCopper} position={[10.695, 248.834, -118.183]} />
      <mesh ref={(el) => setRef(el, "Arm137", 0.5484, 4)} geometry={nodes.Arm137.geometry} material={premiumMaterials.warmGray} position={[0, 248.8, -124.75]} />
      <mesh ref={(el) => setRef(el, "Arm138", 0.9113, 1)} geometry={nodes.Arm138.geometry} material={premiumMaterials.warmGray} position={[1.276, 266.398, -99.237]} />
      <mesh ref={(el) => setRef(el, "Arm139", 0.7177, 5)} geometry={nodes.Arm139.geometry} material={premiumMaterials.warmGray} position={[-0.072, 257.48, -119.894]} />
      <mesh ref={(el) => setRef(el, "Arm140", 0.9677, 0)} geometry={nodes.Arm140.geometry} material={premiumMaterials.gunmetal} position={[0.006, 273.642, -124.748]} />
      <mesh ref={(el) => setRef(el, "Arm141", 1.0000, 0)} geometry={nodes.Arm141.geometry} material={premiumMaterials.darkCopper} position={[-0.005, 278.706, -124.741]} />
      <mesh ref={(el) => setRef(el, "Arm142", 0.4516, 2)} geometry={nodes.Arm142.geometry} material={premiumMaterials.warmGray} position={[-0.008, 245.07, -124.742]} />
      <mesh ref={(el) => setRef(el, "Group_Gripper", 0.9194, 0)} geometry={nodes.Group_Gripper.geometry} material={premiumMaterials.darkCopper} position={[-42.586, 266.857, -265.965]} />
    </group>
  )
}

useGLTF.preload('/roboparadigm-7dof.glb')
