/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/roboparadigm-7dof.glb --draco 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/roboparadigm-7dof.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Arm004.geometry} material={nodes.Arm004.material} position={[-1.735, 255.327, 38.378]} />
      <mesh geometry={nodes.Arm005.geometry} material={nodes.Arm005.material} position={[-4.83, 252.492, 40.419]} />
      <mesh geometry={nodes.Arm006.geometry} material={nodes.Arm006.material} position={[10.236, 265.04, 31.385]} />
      <mesh geometry={nodes.Arm007.geometry} material={nodes.Arm007.material} position={[-0.601, 263.227, 32.691]} />
      <mesh geometry={nodes.Arm008.geometry} material={nodes.Arm008.material} position={[5.178, 260.757, 34.471]} />
      <mesh geometry={nodes.Arm009.geometry} material={nodes.Arm009.material} position={[4.567, 250.057, 42.173]} />
      <mesh geometry={nodes.Arm010.geometry} material={nodes.Arm010.material} position={[6.641, 262.254, 33.402]} />
      <mesh geometry={nodes.Arm011.geometry} material={nodes.Arm011.material} position={[8.304, 255.988, 37.86]} />
      <mesh geometry={nodes.Arm012.geometry} material={nodes.Arm012.material} position={[-9.559, 253.831, 39.455]} />
      <mesh geometry={nodes.Arm013.geometry} material={nodes.Arm013.material} position={[-1.935, 264.535, 31.748]} />
      <mesh geometry={nodes.Arm014.geometry} material={nodes.Arm014.material} position={[12.596, 260.456, 34.686]} />
      <mesh geometry={nodes.Arm017.geometry} material={nodes.Arm017.material} position={[2.022, -20.552, -3.263]} />
      <mesh geometry={nodes.Arm018.geometry} material={nodes.Arm018.material} position={[0.002, -1.178, -3.543]} />
      <mesh geometry={nodes.Arm019.geometry} material={nodes.Arm019.material} position={[3.482, -1.1, -6.737]} />
      <mesh geometry={nodes.Arm020.geometry} material={nodes.Arm020.material} position={[-3.593, -1.35, -2.143]} />
      <mesh geometry={nodes.Arm021.geometry} material={nodes.Arm021.material} position={[-0.029, -1.565, -6.968]} />
      <mesh geometry={nodes.Arm022.geometry} material={nodes.Arm022.material} position={[-0.033, -32.015, -2.684]} />
      <mesh geometry={nodes.Arm023.geometry} material={nodes.Arm023.material} position={[-9.35, -29.6, 19.35]} />
      <mesh geometry={nodes.Arm024.geometry} material={nodes.Arm024.material} position={[9.35, -29.6, 19.35]} />
      <mesh geometry={nodes.Arm025.geometry} material={nodes.Arm025.material} position={[9.208, -30.135, 2.354]} />
      <mesh geometry={nodes.Arm026.geometry} material={nodes.Arm026.material} position={[10.695, -29.416, 5.683]} />
      <mesh geometry={nodes.Arm027.geometry} material={nodes.Arm027.material} position={[-9.208, -30.135, 2.354]} />
      <mesh geometry={nodes.Arm028.geometry} material={nodes.Arm028.material} position={[-10.695, -29.416, 5.683]} />
      <mesh geometry={nodes.Arm029.geometry} material={nodes.Arm029.material} position={[0, -29.45, 12.25]} />
      <mesh geometry={nodes.Arm030.geometry} material={nodes.Arm030.material} position={[-1.276, -11.852, -13.263]} />
      <mesh geometry={nodes.Arm031.geometry} material={nodes.Arm031.material} position={[0.072, -20.77, 7.394]} />
      <mesh geometry={nodes.Arm032.geometry} material={nodes.Arm032.material} position={[-0.006, -4.607, 12.248]} />
      <mesh geometry={nodes.Arm033.geometry} material={nodes.Arm033.material} position={[0.005, 0.457, 12.241]} />
      <mesh geometry={nodes.Arm034.geometry} material={nodes.Arm034.material} position={[0.008, -33.18, 12.242]} />
      <mesh geometry={nodes.Arm037.geometry} material={nodes.Arm037.material} position={[-15.65, 23.763, 8.768]} />
      <mesh geometry={nodes.Arm038.geometry} material={nodes.Arm038.material} position={[-15.4, 28.357, 15.843]} />
      <mesh geometry={nodes.Arm039.geometry} material={nodes.Arm039.material} position={[-15.185, 23.532, 12.279]} />
      <mesh geometry={nodes.Arm041.geometry} material={nodes.Arm041.material} position={[12.85, 49.85, 21.6]} />
      <mesh geometry={nodes.Arm042.geometry} material={nodes.Arm042.material} position={[12.85, 49.85, 2.9]} />
      <mesh geometry={nodes.Arm043.geometry} material={nodes.Arm043.material} position={[13.385, 32.854, 3.042]} />
      <mesh geometry={nodes.Arm044.geometry} material={nodes.Arm044.material} position={[12.666, 36.183, 1.555]} />
      <mesh geometry={nodes.Arm045.geometry} material={nodes.Arm045.material} position={[13.385, 32.854, 21.458]} />
      <mesh geometry={nodes.Arm046.geometry} material={nodes.Arm046.material} position={[12.666, 36.183, 22.945]} />
      <mesh geometry={nodes.Arm047.geometry} material={nodes.Arm047.material} position={[12.7, 42.75, 12.25]} />
      <mesh geometry={nodes.Arm048.geometry} material={nodes.Arm048.material} position={[-4.898, 17.237, 13.526]} />
      <mesh geometry={nodes.Arm049.geometry} material={nodes.Arm049.material} position={[4.02, 37.894, 12.178]} />
      <mesh geometry={nodes.Arm050.geometry} material={nodes.Arm050.material} position={[-12.143, 42.748, 12.256]} />
      <mesh geometry={nodes.Group_Base.geometry} material={nodes.Group_Base.material} position={[-17.207, 42.741, 12.245]} />
      <mesh geometry={nodes.Arm053.geometry} material={nodes.Arm053.material} position={[1.772, 89.448, 9.237]} />
      <mesh geometry={nodes.Arm054.geometry} material={nodes.Arm054.material} position={[-0.248, 108.822, 8.957]} />
      <mesh geometry={nodes.Arm055.geometry} material={nodes.Arm055.material} position={[3.232, 108.9, 5.763]} />
      <mesh geometry={nodes.Arm056.geometry} material={nodes.Arm056.material} position={[-3.843, 108.65, 10.357]} />
      <mesh geometry={nodes.Arm057.geometry} material={nodes.Arm057.material} position={[-0.279, 108.435, 5.532]} />
      <mesh geometry={nodes.Arm058.geometry} material={nodes.Arm058.material} position={[-0.283, 77.984, 9.816]} />
      <mesh geometry={nodes.Arm059.geometry} material={nodes.Arm059.material} position={[-9.6, 80.4, 31.85]} />
      <mesh geometry={nodes.Arm060.geometry} material={nodes.Arm060.material} position={[9.1, 80.4, 31.85]} />
      <mesh geometry={nodes.Arm061.geometry} material={nodes.Arm061.material} position={[8.958, 79.865, 14.854]} />
      <mesh geometry={nodes.Arm062.geometry} material={nodes.Arm062.material} position={[10.445, 80.584, 18.183]} />
      <mesh geometry={nodes.Arm063.geometry} material={nodes.Arm063.material} position={[-9.458, 79.865, 14.854]} />
      <mesh geometry={nodes.Arm064.geometry} material={nodes.Arm064.material} position={[-10.945, 80.584, 18.183]} />
      <mesh geometry={nodes.Arm065.geometry} material={nodes.Arm065.material} position={[-0.25, 80.55, 24.75]} />
      <mesh geometry={nodes.Arm066.geometry} material={nodes.Arm066.material} position={[-1.526, 98.148, -0.763]} />
      <mesh geometry={nodes.Arm067.geometry} material={nodes.Arm067.material} position={[-0.178, 89.23, 19.894]} />
      <mesh geometry={nodes.Arm068.geometry} material={nodes.Arm068.material} position={[-0.256, 105.393, 24.748]} />
      <mesh geometry={nodes.Arm069.geometry} material={nodes.Arm069.material} position={[-0.245, 110.457, 24.741]} />
      <mesh geometry={nodes.Arm070.geometry} material={nodes.Arm070.material} position={[-0.242, 76.821, 24.742]} />
      <mesh geometry={nodes.Group_Lower_Arm.geometry} material={nodes.Group_Lower_Arm.material} position={[-3.552, 252.022, -1.987]} />
      <mesh geometry={nodes.Arm073.geometry} material={nodes.Arm073.material} position={[15.9, 253.482, 1.487]} />
      <mesh geometry={nodes.Arm074.geometry} material={nodes.Arm074.material} position={[15.65, 246.407, -3.107]} />
      <mesh geometry={nodes.Arm075.geometry} material={nodes.Arm075.material} position={[15.435, 249.971, 1.718]} />
      <mesh geometry={nodes.Arm077.geometry} material={nodes.Arm077.material} position={[-12.6, 240.65, -24.6]} />
      <mesh geometry={nodes.Arm078.geometry} material={nodes.Arm078.material} position={[-12.6, 259.35, -24.6]} />
      <mesh geometry={nodes.Arm079.geometry} material={nodes.Arm079.material} position={[-13.135, 259.208, -7.604]} />
      <mesh geometry={nodes.Arm080.geometry} material={nodes.Arm080.material} position={[-12.416, 260.695, -10.933]} />
      <mesh geometry={nodes.Arm081.geometry} material={nodes.Arm081.material} position={[-13.135, 240.792, -7.604]} />
      <mesh geometry={nodes.Arm082.geometry} material={nodes.Arm082.material} position={[-12.416, 239.305, -10.933]} />
      <mesh geometry={nodes.Arm083.geometry} material={nodes.Arm083.material} position={[-12.45, 250, -17.5]} />
      <mesh geometry={nodes.Arm084.geometry} material={nodes.Arm084.material} position={[5.148, 248.724, 8.013]} />
      <mesh geometry={nodes.Arm085.geometry} material={nodes.Arm085.material} position={[-3.77, 250.072, -12.644]} />
      <mesh geometry={nodes.Arm086.geometry} material={nodes.Arm086.material} position={[12.393, 249.994, -17.498]} />
      <mesh geometry={nodes.Arm089.geometry} material={nodes.Arm089.material} position={[2.022, 246.987, -64.948]} />
      <mesh geometry={nodes.Arm090.geometry} material={nodes.Arm090.material} position={[0.002, 246.707, -84.322]} />
      <mesh geometry={nodes.Arm091.geometry} material={nodes.Arm091.material} position={[3.482, 243.513, -84.4]} />
      <mesh geometry={nodes.Arm092.geometry} material={nodes.Arm092.material} position={[-3.593, 248.107, -84.15]} />
      <mesh geometry={nodes.Arm093.geometry} material={nodes.Arm093.material} position={[-0.029, 243.282, -83.935]} />
      <mesh geometry={nodes.Arm094.geometry} material={nodes.Arm094.material} position={[-0.033, 247.566, -53.484]} />
      <mesh geometry={nodes.Arm095.geometry} material={nodes.Arm095.material} position={[-9.35, 269.6, -55.9]} />
      <mesh geometry={nodes.Arm096.geometry} material={nodes.Arm096.material} position={[9.35, 269.6, -55.9]} />
      <mesh geometry={nodes.Arm097.geometry} material={nodes.Arm097.material} position={[9.208, 252.604, -55.365]} />
      <mesh geometry={nodes.Arm098.geometry} material={nodes.Arm098.material} position={[10.695, 255.933, -56.084]} />
      <mesh geometry={nodes.Arm099.geometry} material={nodes.Arm099.material} position={[-9.208, 252.604, -55.365]} />
      <mesh geometry={nodes.Arm100.geometry} material={nodes.Arm100.material} position={[-10.695, 255.933, -56.084]} />
      <mesh geometry={nodes.Arm101.geometry} material={nodes.Arm101.material} position={[0, 262.5, -56.05]} />
      <mesh geometry={nodes.Arm102.geometry} material={nodes.Arm102.material} position={[-1.276, 236.987, -73.648]} />
      <mesh geometry={nodes.Arm103.geometry} material={nodes.Arm103.material} position={[0.072, 257.644, -64.73]} />
      <mesh geometry={nodes.Arm104.geometry} material={nodes.Arm104.material} position={[-0.006, 262.498, -80.893]} />
      <mesh geometry={nodes.Arm106.geometry} material={nodes.Arm106.material} position={[0.008, 262.492, -52.32]} />
      <mesh geometry={nodes['Group_Lower_Arm-2'].geometry} material={nodes['Group_Lower_Arm-2'].material} position={[-15.072, 262.248, -177.457]} />
      <mesh geometry={nodes.Arm109.geometry} material={nodes.Arm109.material} position={[-15.15, 258.768, -174.263]} />
      <mesh geometry={nodes.Arm110.geometry} material={nodes.Arm110.material} position={[-14.9, 265.843, -178.857]} />
      <mesh geometry={nodes.Arm111.geometry} material={nodes.Arm111.material} position={[-14.685, 262.279, -174.032]} />
      <mesh geometry={nodes.Arm113.geometry} material={nodes.Arm113.material} position={[13.35, 271.6, -200.35]} />
      <mesh geometry={nodes.Arm114.geometry} material={nodes.Arm114.material} position={[13.35, 252.9, -200.35]} />
      <mesh geometry={nodes.Arm115.geometry} material={nodes.Arm115.material} position={[13.885, 253.042, -183.354]} />
      <mesh geometry={nodes.Arm116.geometry} material={nodes.Arm116.material} position={[13.166, 251.555, -186.683]} />
      <mesh geometry={nodes.Arm117.geometry} material={nodes.Arm117.material} position={[13.885, 271.458, -183.354]} />
      <mesh geometry={nodes.Arm118.geometry} material={nodes.Arm118.material} position={[13.166, 272.945, -186.683]} />
      <mesh geometry={nodes.Arm119.geometry} material={nodes.Arm119.material} position={[13.2, 262.25, -193.25]} />
      <mesh geometry={nodes.Arm120.geometry} material={nodes.Arm120.material} position={[-4.398, 263.526, -167.737]} />
      <mesh geometry={nodes.Arm121.geometry} material={nodes.Arm121.material} position={[4.52, 262.178, -188.394]} />
      <mesh geometry={nodes.Arm122.geometry} material={nodes.Arm122.material} position={[-11.643, 262.256, -193.248]} />
      <mesh geometry={nodes.Arm123.geometry} material={nodes.Arm123.material} position={[-16.707, 262.245, -193.241]} />
      <mesh geometry={nodes.Arm124.geometry} material={nodes.Arm124.material} position={[16.93, 262.242, -193.242]} />
      <mesh geometry={nodes.Arm127.geometry} material={nodes.Arm127.material} position={[-3.482, 277.15, -105.763]} />
      <mesh geometry={nodes.Arm128.geometry} material={nodes.Arm128.material} position={[3.593, 276.9, -110.357]} />
      <mesh geometry={nodes.Arm129.geometry} material={nodes.Arm129.material} position={[0.029, 276.685, -105.532]} />
      <mesh geometry={nodes['Group_Lower_Arm-1'].geometry} material={nodes['Group_Lower_Arm-1'].material} position={[0.033, 246.235, -109.816]} />
      <mesh geometry={nodes.Arm131.geometry} material={nodes.Arm131.material} position={[9.35, 248.65, -131.85]} />
      <mesh geometry={nodes.Arm132.geometry} material={nodes.Arm132.material} position={[-9.35, 248.65, -131.85]} />
      <mesh geometry={nodes.Arm133.geometry} material={nodes.Arm133.material} position={[-9.208, 248.115, -114.854]} />
      <mesh geometry={nodes.Arm134.geometry} material={nodes.Arm134.material} position={[-10.695, 248.834, -118.183]} />
      <mesh geometry={nodes.Arm135.geometry} material={nodes.Arm135.material} position={[9.208, 248.115, -114.854]} />
      <mesh geometry={nodes.Arm136.geometry} material={nodes.Arm136.material} position={[10.695, 248.834, -118.183]} />
      <mesh geometry={nodes.Arm137.geometry} material={nodes.Arm137.material} position={[0, 248.8, -124.75]} />
      <mesh geometry={nodes.Arm138.geometry} material={nodes.Arm138.material} position={[1.276, 266.398, -99.237]} />
      <mesh geometry={nodes.Arm139.geometry} material={nodes.Arm139.material} position={[-0.072, 257.48, -119.894]} />
      <mesh geometry={nodes.Arm140.geometry} material={nodes.Arm140.material} position={[0.006, 273.642, -124.748]} />
      <mesh geometry={nodes.Arm141.geometry} material={nodes.Arm141.material} position={[-0.005, 278.706, -124.741]} />
      <mesh geometry={nodes.Arm142.geometry} material={nodes.Arm142.material} position={[-0.008, 245.07, -124.742]} />
      <mesh geometry={nodes.Group_Gripper.geometry} material={nodes.Group_Gripper.material} position={[-42.586, 266.857, -265.965]} />
    </group>
  )
}

useGLTF.preload('/roboparadigm-7dof.glb')
